### PR TITLE
Inject runtime install calls before anything else

### PR DESCRIPTION
**Pull request by arichiardi**
As per title

### CODE REVIEW

**Comment by jupl** [comment]
What is the difference between the two? I don't understand.

**Comment by jupl** [comment]
It's under threading `->` though.

**Comment by arichiardi** [comment]
Uhm the first param is % so it should work, but now i have some doubt actually ;) let me try it out and get back to you ok?

**Comment by superstructor** [comment]
Built a snapshot of the `install-order` branch and verified that this does fix being able to breakpoint on app init functions. i.e. devtools etc is correctly installed ​_before_​ other init fns instead of after which is the current behaviour.

**Comment by arichiardi** [comment]
Yes the patch works because it is not threading, `update-in` wants a function as 3rd argument.

**Comment by arichiardi** [comment]
By the way, the Cljs core team is thinking of adding a `:preloads` compiler option (thanks @superstructor) and therefore this might be obsolete soon, but still...it is better to add it and keep this task up to speed...

**Comment by superstructor** [comment]
Things move fast, David Nolen released `[org.clojure/clojurescript "1.9.88"]` today which includes the [`:preloads`](https://github.com/clojure/clojurescript/blob/master/src/main/clojure/cljs/closure.clj#L912) compiler option which is a seq of symbols that correspond to namespaces to load [before main](https://github.com/clojure/clojurescript/blob/master/src/main/clojure/cljs/closure.clj#L1441) and immediately after `cljs.core` or the constants table depending on the optimization setting.

`[binaryage/devtools "0.7.2"]` was also released thanks to @darwin which includes a [`devtools.preload`](https://github.com/binaryage/cljs-devtools/blob/master/src/lib/devtools/preload.cljs) ns.

I didn't have anything to do with the work but this is just what I have seen on Clojurians and GitHub.

**Pull request merged**
